##**<font color='#BF4AD4'>Cargue de librerias</font>**

In [ ]:
import pandas as pd
from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## **<font color='#3498DB'>Cargue del dataframe</font>**

In [ ]:
url = "https://raw.githubusercontent.com/Omaira85/BASES-DE-DATOS-SEG-SEMESTRE/main/Pueblo%20indigena1.csv"
puebloindigena = pd.read_csv(url, sep=';', encoding = 'unicode_escape')
puebloindigena

,Código,Departamento,Población total,Maya,Garífuna,Xinka,Afrodescendiente / Creole / Afromestizo,Ladina(o),Extranjera(o)
0,NaN,Total nacional,14901286,6207503,19529,264167,27647,8346120,36320
1,1.0,Guatemala,3 015 081,402 376,4 583,3 382,6 222,2 578 135,20 383
2,2.0,El Progreso,176 632,2 627,184,46,86,173 441,248
3,3.0,Sacatepéquez,330 469,132 762,428,206,486,195 101,1 486
4,4.0,Chimaltenango,615 776,481 335,563,237,1 255,131 674,712
5,5.0,Escuintla,733 181,37 100,933,259,1 466,691 936,1 487
6,6.0,Santa Rosa,396 607,7 863,646,55 855,885,330 149,1 209
7,7.0,Sololá,421 583,406 295,387,35,366,14 025,475
8,8.0,Totonicapán,418 569,410 195,274,49,381,7 528,142
9,9.0,Quetzaltenango,799 101,406 491,675,206,1 197,388 850,1 682
10,10.0,Suchitepéquez,554 695,211 103,639,210,3 531,338 471,741
11,11.0,Retalhuleu,326 828,48 871,258,58,684,276 576,381
12,12.0,San Marcos,1 032 277,318 093,757,76,495,711 812,1 044
13,13.0,Huehuetenango,1 170 669,760 871,884,44,1 305,406 836,729
14,14.0,Quiché,949 261,846 500,556,59,1 690,100 150,306
15,15.0,Baja Verapaz,299 476,179 746,244,63,542,118 660,221
16,16.0,Alta Verapaz,1 215 038,1 129 369,1 136,147,1 288,82 505,593
17,17.0,Petén,545 600,164 814,462,200,1 097,378 129,898
18,18.0,Izabal,408 688,115 296,3 002,105,1 529,287 869,887
19,19.0,Zacapa,245 374,4 769,349,46,791,238 987,432
20,20.0,Chiquimula,415 063,111 368,797,49,771,301 454,624
21,21.0,Jalapa,342 923,24 891,832,108 529,690,207 497,484
22,22.0,Jutiapa,488 395,4 768,940,94 306,890,386 335,1 156

## **<font color='#3498DB'>Limpieza</font>**

### **Eliminación de tildes**

In [ ]:
import unicodedata

def strip_accents(s):
  if (type(s) == str):
    return ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn')
  return s




for column in puebloindigena.keys():
  puebloindigena[column] = puebloindigena[column].map(strip_accents)

puebloindigena

,Código,Departamento,Población total,Maya,Garífuna,Xinka,Afrodescendiente / Creole / Afromestizo,Ladina(o),Extranjera(o)
0,NaN,Total nacional,14901286,6207503,19529,264167,27647,8346120,36320
1,1.0,Guatemala,3 015 081,402 376,4 583,3 382,6 222,2 578 135,20 383
2,2.0,El Progreso,176 632,2 627,184,46,86,173 441,248
3,3.0,Sacatepequez,330 469,132 762,428,206,486,195 101,1 486
4,4.0,Chimaltenango,615 776,481 335,563,237,1 255,131 674,712
5,5.0,Escuintla,733 181,37 100,933,259,1 466,691 936,1 487
6,6.0,Santa Rosa,396 607,7 863,646,55 855,885,330 149,1 209
7,7.0,Solola,421 583,406 295,387,35,366,14 025,475
8,8.0,Totonicapan,418 569,410 195,274,49,381,7 528,142
9,9.0,Quetzaltenango,799 101,406 491,675,206,1 197,388 850,1 682
10,10.0,Suchitepequez,554 695,211 103,639,210,3 531,338 471,741
11,11.0,Retalhuleu,326 828,48 871,258,58,684,276 576,381
12,12.0,San Marcos,1 032 277,318 093,757,76,495,711 812,1 044
13,13.0,Huehuetenango,1 170 669,760 871,884,44,1 305,406 836,729
14,14.0,Quiche,949 261,846 500,556,59,1 690,100 150,306
15,15.0,Baja Verapaz,299 476,179 746,244,63,542,118 660,221
16,16.0,Alta Verapaz,1 215 038,1 129 369,1 136,147,1 288,82 505,593
17,17.0,Peten,545 600,164 814,462,200,1 097,378 129,898
18,18.0,Izabal,408 688,115 296,3 002,105,1 529,287 869,887
19,19.0,Zacapa,245 374,4 769,349,46,791,238 987,432
20,20.0,Chiquimula,415 063,111 368,797,49,771,301 454,624
21,21.0,Jalapa,342 923,24 891,832,108 529,690,207 497,484
22,22.0,Jutiapa,488 395,4 768,940,94 306,890,386 335,1 156

### **Cambio nombre de columnas**

In [ ]:
puebloindigena.columns = ['CODIGO', 'DEPARTAMENTO', 'POBLACION_TOTAL', 'PDP_MAYA','PDP_GARIFUNA','PDP_XINCA', 'PDP_AFRODESCENDIENTE/CREOLE/AFROMESTIZO', 'PDP_LADINA(O)','PDP_EXTRANJERA(O)' ]

In [ ]:
puebloindigena

,CODIGO,DEPARTAMENTO,POBLACION_TOTAL,PDP_MAYA,PDP_GARIFUNA,PDP_XINCA,PDP_AFRODESCENDIENTE/CREOLE/AFROMESTIZO,PDP_LADINA(O),PDP_EXTRANJERA(O)
0,NaN,Total nacional,14901286,6207503,19529,264167,27647,8346120,36320
1,1.0,Guatemala,3 015 081,402 376,4 583,3 382,6 222,2 578 135,20 383
2,2.0,El Progreso,176 632,2 627,184,46,86,173 441,248
3,3.0,Sacatepequez,330 469,132 762,428,206,486,195 101,1 486
4,4.0,Chimaltenango,615 776,481 335,563,237,1 255,131 674,712
5,5.0,Escuintla,733 181,37 100,933,259,1 466,691 936,1 487
6,6.0,Santa Rosa,396 607,7 863,646,55 855,885,330 149,1 209
7,7.0,Solola,421 583,406 295,387,35,366,14 025,475
8,8.0,Totonicapan,418 569,410 195,274,49,381,7 528,142
9,9.0,Quetzaltenango,799 101,406 491,675,206,1 197,388 850,1 682
10,10.0,Suchitepequez,554 695,211 103,639,210,3 531,338 471,741
11,11.0,Retalhuleu,326 828,48 871,258,58,684,276 576,381
12,12.0,San Marcos,1 032 277,318 093,757,76,495,711 812,1 044
13,13.0,Huehuetenango,1 170 669,760 871,884,44,1 305,406 836,729
14,14.0,Quiche,949 261,846 500,556,59,1 690,100 150,306
15,15.0,Baja Verapaz,299 476,179 746,244,63,542,118 660,221
16,16.0,Alta Verapaz,1 215 038,1 129 369,1 136,147,1 288,82 505,593
17,17.0,Peten,545 600,164 814,462,200,1 097,378 129,898
18,18.0,Izabal,408 688,115 296,3 002,105,1 529,287 869,887
19,19.0,Zacapa,245 374,4 769,349,46,791,238 987,432
20,20.0,Chiquimula,415 063,111 368,797,49,771,301 454,624
21,21.0,Jalapa,342 923,24 891,832,108 529,690,207 497,484
22,22.0,Jutiapa,488 395,4 768,940,94 306,890,386 335,1 156

### **Informacion de la base y tipos de variables de cada una de las columnas del Dataframe**

In [ ]:
puebloindigena.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 9 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   CODIGO                                   22 non-null     float64
 1   DEPARTAMENTO                             23 non-null     object
 2   POBLACION_TOTAL                          23 non-null     object
 3   PDP_MAYA                                 23 non-null     object
 4   PDP_GARIFUNA                             23 non-null     object
 5   PDP_XINCA                                23 non-null     object
 6   PDP_AFRODESCENDIENTE/CREOLE/AFROMESTIZO  23 non-null     object
 7   PDP_LADINA(O)                            23 non-null     object
 8   PDP_EXTRANJERA(O)                        23 non-null     object
dtypes: float64(1), object(8)
memory usage: 1.7+ KB

### **Se remplazan espacios en blanco por ningún valor**

In [ ]:
def remover_espacio(cadena):
  return cadena.replace(" ", "", regex = True)

In [ ]:
puebloindigena.iloc[:, 2:9] = remover_espacio(puebloindigena.iloc[:, 2:9])

In [ ]:
puebloindigena

,CODIGO,DEPARTAMENTO,POBLACION_TOTAL,PDP_MAYA,PDP_GARIFUNA,PDP_XINCA,PDP_AFRODESCENDIENTE/CREOLE/AFROMESTIZO,PDP_LADINA(O),PDP_EXTRANJERA(O)
0,NaN,Total nacional,14901286,6207503,19529,264167,27647,8346120,36320
1,1.0,Guatemala,3015081,402376,4583,3382,6222,2578135,20383
2,2.0,El Progreso,176632,2627,184,46,86,173441,248
3,3.0,Sacatepequez,330469,132762,428,206,486,195101,1486
4,4.0,Chimaltenango,615776,481335,563,237,1255,131674,712
5,5.0,Escuintla,733181,37100,933,259,1466,691936,1487
6,6.0,Santa Rosa,396607,7863,646,55855,885,330149,1209
7,7.0,Solola,421583,406295,387,35,366,14025,475
8,8.0,Totonicapan,418569,410195,274,49,381,7528,142
9,9.0,Quetzaltenango,799101,406491,675,206,1197,388850,1682
10,10.0,Suchitepequez,554695,211103,639,210,3531,338471,741
11,11.0,Retalhuleu,326828,48871,258,58,684,276576,381
12,12.0,San Marcos,1032277,318093,757,76,495,711812,1044
13,13.0,Huehuetenango,1170669,760871,884,44,1305,406836,729
14,14.0,Quiche,949261,846500,556,59,1690,100150,306
15,15.0,Baja Verapaz,299476,179746,244,63,542,118660,221
16,16.0,Alta Verapaz,1215038,1129369,1136,147,1288,82505,593
17,17.0,Peten,545600,164814,462,200,1097,378129,898
18,18.0,Izabal,408688,115296,3002,105,1529,287869,887
19,19.0,Zacapa,245374,4769,349,46,791,238987,432
20,20.0,Chiquimula,415063,111368,797,49,771,301454,624
21,21.0,Jalapa,342923,24891,832,108529,690,207497,484
22,22.0,Jutiapa,488395,4768,940,94306,890,386335,1156

### **Se cambian tipos de datos de object a int64**

In [ ]:
puebloindigena = puebloindigena.astype({'POBLACION_TOTAL': 'int64', 'PDP_MAYA': 'int64', 'PDP_GARIFUNA': 'int64', 'PDP_XINCA': 'int64', 'PDP_AFRODESCENDIENTE/CREOLE/AFROMESTIZO': 'int64', 'PDP_LADINA(O)': 'int64', 'PDP_EXTRANJERA(O)': 'int64'})

### **Informacion de la base y tipos de variables de cada una de las columnas del Dataframe**

In [ ]:
puebloindigena.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 9 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   CODIGO                                   22 non-null     float64
 1   DEPARTAMENTO                             23 non-null     object
 2   POBLACION_TOTAL                          23 non-null     int64
 3   PDP_MAYA                                 23 non-null     int64
 4   PDP_GARIFUNA                             23 non-null     int64
 5   PDP_XINCA                                23 non-null     int64
 6   PDP_AFRODESCENDIENTE/CREOLE/AFROMESTIZO  23 non-null     int64
 7   PDP_LADINA(O)                            23 non-null     int64
 8   PDP_EXTRANJERA(O)                        23 non-null     int64
dtypes: float64(1), int64(7), object(1)
memory usage: 1.7+ KB

In [ ]:
puebloindigena

,CODIGO,DEPARTAMENTO,POBLACION_TOTAL,PDP_MAYA,PDP_GARIFUNA,PDP_XINCA,PDP_AFRODESCENDIENTE/CREOLE/AFROMESTIZO,PDP_LADINA(O),PDP_EXTRANJERA(O)
0,NaN,Total nacional,14901286,6207503,19529,264167,27647,8346120,36320
1,1.0,Guatemala,3015081,402376,4583,3382,6222,2578135,20383
2,2.0,El Progreso,176632,2627,184,46,86,173441,248
3,3.0,Sacatepequez,330469,132762,428,206,486,195101,1486
4,4.0,Chimaltenango,615776,481335,563,237,1255,131674,712
5,5.0,Escuintla,733181,37100,933,259,1466,691936,1487
6,6.0,Santa Rosa,396607,7863,646,55855,885,330149,1209
7,7.0,Solola,421583,406295,387,35,366,14025,475
8,8.0,Totonicapan,418569,410195,274,49,381,7528,142
9,9.0,Quetzaltenango,799101,406491,675,206,1197,388850,1682
10,10.0,Suchitepequez,554695,211103,639,210,3531,338471,741
11,11.0,Retalhuleu,326828,48871,258,58,684,276576,381
12,12.0,San Marcos,1032277,318093,757,76,495,711812,1044
13,13.0,Huehuetenango,1170669,760871,884,44,1305,406836,729
14,14.0,Quiche,949261,846500,556,59,1690,100150,306
15,15.0,Baja Verapaz,299476,179746,244,63,542,118660,221
16,16.0,Alta Verapaz,1215038,1129369,1136,147,1288,82505,593
17,17.0,Peten,545600,164814,462,200,1097,378129,898
18,18.0,Izabal,408688,115296,3002,105,1529,287869,887
19,19.0,Zacapa,245374,4769,349,46,791,238987,432
20,20.0,Chiquimula,415063,111368,797,49,771,301454,624
21,21.0,Jalapa,342923,24891,832,108529,690,207497,484
22,22.0,Jutiapa,488395,4768,940,94306,890,386335,1156

In [ ]:
puebloindigena.to_csv('puebloindigena1.csv')
files.download('puebloindigena1.csv')

## **<font color='#3498DB'>Cargue Dataframe Acceso Internet</font>**

>  Características generales de la población. Censo 2018: Este dataframe contiene la información de la población de 7 años o más por uso de celular, computadora y/o internet, de acuerdo al municipio

In [ ]:
accesointernet = pd.read_excel("/content/drive/MyDrive/Base de Datos/Acceso Internet.xlsx")
accesointernet

,Código Departamento,Código Municipio,Medio Tecnologico,Utiliza,Cantidad
0,7,701,celular,Usa,47386
1,7,702,celular,Usa,1925
2,7,703,celular,Usa,1591
3,7,704,celular,Usa,11922
4,7,705,celular,Usa,31939
...,...,...,...,...,...
1438,14,1417,Computadora e internet,Usa,318
1439,14,1418,Computadora e internet,Usa,880
1440,14,1419,Computadora e internet,Usa,1757
1441,14,1420,Computadora e internet,Usa,6094
1442,14,1421,Computadora e internet,Usa,1198

In [ ]:
import unicodedata

def strip_accents(s):
  if (type(s) == str):
    return ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn')
  return s




for column in accesointernet.keys():
  accesointernet[column] = accesointernet[column].map(strip_accents)

accesointernet

,Código Departamento,Código Municipio,Medio Tecnologico,Utiliza,Cantidad
0,7,701,celular,Usa,47386
1,7,702,celular,Usa,1925
2,7,703,celular,Usa,1591
3,7,704,celular,Usa,11922
4,7,705,celular,Usa,31939
...,...,...,...,...,...
1438,14,1417,Computadora e internet,Usa,318
1439,14,1418,Computadora e internet,Usa,880
1440,14,1419,Computadora e internet,Usa,1757
1441,14,1420,Computadora e internet,Usa,6094
1442,14,1421,Computadora e internet,Usa,1198

In [ ]:
accesointernet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1443 entries, 0 to 1442
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Código Departamento  1443 non-null   int64
 1   Código Municipio     1443 non-null   int64
 2   Medio Tecnologico    1443 non-null   object
 3   Utiliza              1443 non-null   object
 4   Cantidad             1443 non-null   int64
dtypes: int64(3), object(2)
memory usage: 56.5+ KB

In [30]:
accesointernet.to_csv('accesointernet.csv')
files.download('accesointernet.csv')